#!/usr/bin/env node
const { spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');

function now() { return new Date().toISOString(); }

function run(cmd, args, opts) {
  // On Windows, npm and npx are .cmd shims (npm.cmd / npx.cmd). Use the
  // .cmd variant when appropriate so spawnSync can find the executable.
  const winShimCmds = new Set(['npm', 'npx']);
  const execCmd = process.platform === 'win32' && winShimCmds.has(cmd) ? `${cmd}.cmd` : cmd;
  const full = `${execCmd} ${args.join(' ')}`.trim();
  if (opts.dryRun) {
    return { status: 0, stdout: `[dry-run] would run: ${full}\n`, stderr: '' };
  }
  try {
    const res = spawnSync(execCmd, args, { encoding: 'utf8', shell: false });
    return {
      status: res.status === null ? 1 : res.status,
      stdout: res.stdout || '',
      stderr: res.stderr || '',
      signal: res.signal || null,
      error: res.error || null,
      // include the raw output array for extra diagnostics if needed
      output: res.output || null,
    };
  } catch (e) {
    return { status: 1, stdout: '', stderr: String(e), error: e };
  }
}

function parseArgs() {
  const a = process.argv.slice(2);
  // support --dry-run and --out <path> to control output file
  const dryRun = a.includes('--dry-run') || process.env.DRY_RUN === '1';
  const outIndex = a.indexOf('--out');
  const out = outIndex !== -1 && a.length > outIndex + 1 ? a[outIndex + 1] : process.env.OUT_FILE;
  return { dryRun, out };
}

const argv = parseArgs();
const outDir = path.join(process.cwd(), 'docs', 'changes');
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
// Compute the default output filename by scanning the docs/changes
// directory for the highest existing iteration-NNN.md and incrementing
// it. This avoids manually bumping the hardcoded filename each run.
function nextIterationDefault(dir) {
  const files = fs.readdirSync(dir);
  let max = 0;
  const re = /^iteration-(\d+)\.md$/;
  for (const f of files) {
    const m = f.match(re);
    if (m) {
      const n = parseInt(m[1], 10);
      if (!Number.isNaN(n) && n > max) max = n;
    }
  }
  const next = max + 1 || 1;
  const pad = String(next).padStart(3, '0');
  return path.join(dir, `iteration-${pad}.md`);
}

const defaultOut = nextIterationDefault(outDir);
const outFile = argv.out ? (path.isAbsolute(argv.out) ? argv.out : path.join(process.cwd(), argv.out)) : defaultOut;

// Derive a human-friendly header from the output filename so the generated
// docs header always matches the file name (fixes header/content mismatches).
const outBase = path.basename(outFile, path.extname(outFile));
const log = [];
log.push(`# Automated e2e Agent Run - ${outBase}`);
log.push('');
log.push(`timestamp: ${now()}`);
log.push('');
log.push('This file was generated by scripts/automate-e2e.js. It captures the sequence of commands an automated UI-testing agent should run and their outputs.');
log.push('');

const steps = [
  { name: 'npm ci', cmd: 'npm', args: ['ci'] },
  { name: 'e2e:prep', cmd: 'npm', args: ['run', 'e2e:prep'] },
  { name: 'e2e', cmd: 'npm', args: ['run', 'e2e'] },
];

let previousFailed = false;
// Check for expected devDependencies / local bin helpers before running
// network- or tool-dependent steps. This gives clearer guidance when the
// environment lacks protractor/webdriver-manager or when devDependencies
// have not been installed (common in CI/workspace runs).
function checkDevDeps() {
  const msgs = [];
  let ok = true;
  try {
    const pkgPath = path.join(process.cwd(), 'package.json');
    if (fs.existsSync(pkgPath)) {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
      const dev = pkg.devDependencies || {};
      if (!dev.protractor && !dev['webdriver-manager']) {
        msgs.push('package.json does not list protractor or webdriver-manager in devDependencies.');
        ok = false;
      }
    } else {
      msgs.push('package.json not found in workspace root.');
      ok = false;
    }
  } catch (e) {
    msgs.push('Failed to read/parse package.json: ' + String(e));
    ok = false;
  }

  // Check node_modules/.bin for expected binaries
  const binDir = path.join(process.cwd(), 'node_modules', '.bin');
  const protractorBin = process.platform === 'win32' ? 'protractor.cmd' : 'protractor';
  const webdriverBin = process.platform === 'win32' ? 'webdriver-manager.cmd' : 'webdriver-manager';
  if (!fs.existsSync(path.join(binDir, protractorBin))) {
    msgs.push(`Local protractor binary not found at ${path.join('node_modules', '.bin', protractorBin)}.`);
    ok = false;
  }
  if (!fs.existsSync(path.join(binDir, webdriverBin))) {
    msgs.push(`Local webdriver-manager binary not found at ${path.join('node_modules', '.bin', webdriverBin)}.`);
    ok = false;
  }

  return { ok, msgs };
}

// Emit a pre-flight check as Step 0 so it's recorded in the generated log
const preflight = checkDevDeps();
log.push('## Step 0: Preflight devDependencies check');
log.push('');
log.push('This check verifies package.json and local node_modules binaries required for e2e runs.');
log.push('');
if (preflight.ok) {
  log.push('_Preflight check passed: devDependencies and local binaries appear present._');
  log.push('');
} else {
  log.push('_Preflight check failed: missing devDependencies or local binaries._');
  log.push('');
  for (const m of preflight.msgs) {
    log.push('- ' + m);
  }
  log.push('');
  log.push('Action: Run `npm ci` (or `npm i -D protractor webdriver-manager`) in the project root to install devDependencies, then re-run the agent.');
  log.push('');
  // Prevent further steps from running when preflight fails; the agent should
  // install dependencies first and re-run to capture meaningful webdriver-manager output.
  previousFailed = true;
}
for (let i = 0; i < steps.length; i++) {
  const s = steps[i];
  log.push(`## Step ${i+1}: ${s.name}`);
  log.push('');
  log.push(`Command: ${s.cmd} ${s.args.join(' ')}`);
  log.push('');

  if (previousFailed) {
    log.push('_Skipped because a previous step failed_');
    log.push('');
    continue;
  }

  const res = run(s.cmd, s.args, { dryRun: argv.dryRun });
  log.push('Exit Code: ' + (res.status == null ? 'null' : String(res.status)));
  log.push('');
  if (res.stdout && res.stdout.trim()) {
    log.push('Stdout:');
    log.push('');
    log.push('```');
    log.push(res.stdout.trim());
    log.push('```');
    log.push('');
  }
  if (res.stderr && res.stderr.trim()) {
    log.push('Stderr:');
    log.push('');
    log.push('```');
    log.push(res.stderr.trim());
    log.push('```');
    log.push('');
  }

  if (res.status !== 0) {
    previousFailed = true;
    log.push(`_Step failed with exit code ${res.status}_`);
    log.push('');
    // Add actionable guidance
    if (s.name === 'npm ci') {
      log.push('Action: Ensure the environment has network access and npm registry reachable, or run `npm ci` locally and re-run the agent.');
      log.push('');
      // Detect an npm ERESOLVE / peer dependency resolution failure and
      // attempt a single retry with the legacy peer deps flag. This is a
      // pragmatic fallback for CI environments where peer conflicts are
      // acceptable and prevents the agent from failing without guidance.
      const stderrLower = (res.stderr || '').toLowerCase();
      if (stderrLower.includes('eresolve') || stderrLower.includes('peer')) {
        log.push('Detected a dependency resolution (ERESOLVE) during `npm ci`. Retrying once with `--legacy-peer-deps`...');
        log.push('');
        const retry = run('npm', ['ci', '--legacy-peer-deps'], { dryRun: argv.dryRun });
        log.push('Retry Exit Code: ' + (retry.status == null ? 'null' : String(retry.status)));
        log.push('');
        if (retry.stdout && retry.stdout.trim()) {
          log.push('Retry Stdout:');
          log.push('');
          log.push('```');
          log.push(retry.stdout.trim());
          log.push('```');
          log.push('');
        }
        if (retry.stderr && retry.stderr.trim()) {
          log.push('Retry Stderr:');
          log.push('');
          log.push('```');
          log.push(retry.stderr.trim());
          log.push('```');
          log.push('');
        }
        if (retry.status === 0) {
          // Consider the retry a success and allow subsequent steps to run.
          previousFailed = false;
          log.push('_Retry with --legacy-peer-deps succeeded; continuing with remaining steps._');
          log.push('');
        } else {
          log.push('_Retry with --legacy-peer-deps also failed._');
          log.push('Action: Consider running `npm ci --legacy-peer-deps` manually or reconciling peer dependency versions in package.json.');
          log.push('');
        }
      }
    }
    if (s.name === 'e2e:prep') {
      log.push('Action: If update-chromedriver failed, consider re-running with `node scripts/update-chromedriver.js --no-update` to see the intended command or set CHROME_MAJOR to override detection.');
      log.push('');
    }
  }
}

log.push('');
log.push('## Summary');
log.push('');
if (argv.dryRun) {
  log.push('*Run executed in dry-run mode; no commands were actually run.*');
} else if (previousFailed) {
  log.push('*One or more steps failed — see above logs for details.*');
} else {
  log.push('*All steps completed successfully.*');
}
log.push('');

// Write the log file and verify it was written successfully. This helps
// detect timing/path issues when verification tools check for the file
// immediately after this script completes.
fs.writeFileSync(outFile, log.join('\n'), 'utf8');
const resolvedOut = path.resolve(outFile);
if (fs.existsSync(resolvedOut)) {
  try {
    const stats = fs.statSync(resolvedOut);
    if (stats.size > 0) {
      console.log('Wrote logs to', resolvedOut);
      if (argv.dryRun) process.exit(0);
      process.exit(previousFailed ? 2 : 0);
    } else {
      console.error('Log file was created but is empty:', resolvedOut);
      process.exit(3);
    }
  } catch (e) {
    console.error('Wrote log but could not stat the file:', resolvedOut, String(e));
    process.exit(3);
  }
} else {
  console.error('Failed to write logs to', resolvedOut);
  process.exit(3);
}
