#!/usr/bin/env node
const { spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');

function now() { return new Date().toISOString(); }

function run(cmd, args, opts) {
  // On Windows, npm and npx are .cmd shims (npm.cmd / npx.cmd). Use the
  // .cmd variant when appropriate so spawnSync can find the executable.
  const winShimCmds = new Set(['npm', 'npx']);
  const execCmd = process.platform === 'win32' && winShimCmds.has(cmd) ? `${cmd}.cmd` : cmd;
  const full = `${execCmd} ${args.join(' ')}`.trim();
  if (opts.dryRun) {
    return { status: 0, stdout: `[dry-run] would run: ${full}\n`, stderr: '' };
  }
  try {
    const res = spawnSync(execCmd, args, { encoding: 'utf8', shell: false });
    return { status: res.status === null ? 1 : res.status, stdout: res.stdout || '', stderr: res.stderr || '' };
  } catch (e) {
    return { status: 1, stdout: '', stderr: String(e) };
  }
}

function parseArgs() {
  const a = process.argv.slice(2);
  // support --dry-run and --out <path> to control output file
  const dryRun = a.includes('--dry-run') || process.env.DRY_RUN === '1';
  const outIndex = a.indexOf('--out');
  const out = outIndex !== -1 && a.length > outIndex + 1 ? a[outIndex + 1] : process.env.OUT_FILE;
  return { dryRun, out };
}

const argv = parseArgs();
const outDir = path.join(process.cwd(), 'docs', 'changes');
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
const defaultOut = path.join(outDir, 'iteration-018.md');
const outFile = argv.out ? path.isAbsolute(argv.out) ? argv.out : path.join(process.cwd(), argv.out) : defaultOut;

// Derive a human-friendly header from the output filename so the generated
// docs header always matches the file name (fixes header/content mismatches).
const outBase = path.basename(outFile, path.extname(outFile));
const log = [];
log.push(`# Automated e2e Agent Run - ${outBase}`);
log.push('');
log.push(`timestamp: ${now()}`);
log.push('');
log.push('This file was generated by scripts/automate-e2e.js. It captures the sequence of commands an automated UI-testing agent should run and their outputs.');
log.push('');

const steps = [
  { name: 'npm ci', cmd: 'npm', args: ['ci'] },
  { name: 'e2e:prep', cmd: 'npm', args: ['run', 'e2e:prep'] },
  { name: 'e2e', cmd: 'npm', args: ['run', 'e2e'] },
];

let previousFailed = false;
for (let i = 0; i < steps.length; i++) {
  const s = steps[i];
  log.push(`## Step ${i+1}: ${s.name}`);
  log.push('');
  log.push(`Command: ${s.cmd} ${s.args.join(' ')}`);
  log.push('');

  if (previousFailed) {
    log.push('_Skipped because a previous step failed_');
    log.push('');
    continue;
  }

  const res = run(s.cmd, s.args, { dryRun: argv.dryRun });
  log.push('Exit Code: ' + (res.status == null ? 'null' : String(res.status)));
  log.push('');
  if (res.stdout && res.stdout.trim()) {
    log.push('Stdout:');
    log.push('');
    log.push('```');
    log.push(res.stdout.trim());
    log.push('```');
    log.push('');
  }
  if (res.stderr && res.stderr.trim()) {
    log.push('Stderr:');
    log.push('');
    log.push('```');
    log.push(res.stderr.trim());
    log.push('```');
    log.push('');
  }

  if (res.status !== 0) {
    previousFailed = true;
    log.push(`_Step failed with exit code ${res.status}_`);
    log.push('');
    // Add actionable guidance
    if (s.name === 'npm ci') {
      log.push('Action: Ensure the environment has network access and npm registry reachable, or run `npm ci` locally and re-run the agent.');
      log.push('');
    }
    if (s.name === 'e2e:prep') {
      log.push('Action: If update-chromedriver failed, consider re-running with `node scripts/update-chromedriver.js --no-update` to see the intended command or set CHROME_MAJOR to override detection.');
      log.push('');
    }
  }
}

log.push('');
log.push('## Summary');
log.push('');
if (argv.dryRun) {
  log.push('*Run executed in dry-run mode; no commands were actually run.*');
} else if (previousFailed) {
  log.push('*One or more steps failed — see above logs for details.*');
} else {
  log.push('*All steps completed successfully.*');
}
log.push('');

// Write the log file and verify it was written successfully. This helps
// detect timing/path issues when verification tools check for the file
// immediately after this script completes.
fs.writeFileSync(outFile, log.join('\n'), 'utf8');
const resolvedOut = path.resolve(outFile);
if (fs.existsSync(resolvedOut)) {
  try {
    const stats = fs.statSync(resolvedOut);
    if (stats.size > 0) {
      console.log('Wrote logs to', resolvedOut);
      if (argv.dryRun) process.exit(0);
      process.exit(previousFailed ? 2 : 0);
    } else {
      console.error('Log file was created but is empty:', resolvedOut);
      process.exit(3);
    }
  } catch (e) {
    console.error('Wrote log but could not stat the file:', resolvedOut, String(e));
    process.exit(3);
  }
} else {
  console.error('Failed to write logs to', resolvedOut);
  process.exit(3);
}
